[project]
python_requires = ">=3.10"

[tool.black]
line-length = 88
target-version = ["py310"]
include = '\.pyi?$'

[tool.ruff]
exclude = ["tests"]
line-length = 88
src = ["src"]

[tool.ruff.lint]
select = ["A", "B", "E", "I"]
ignore = ["E501"]
