# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on:
  push:
    branches: [ "master", "webhooks-render"]
  pull_request:
    branches: [ "master", "webhooks-render"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check codestyle with pre-commit
      run: |
        pip install pre-commit
        pre-commit run --all-files --show-diff-on-failure
    - name: Test with unittest
      run: |
         python -m unittest discover -s tests/ -p test_*.py
